---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.10.24
  environments_path: ./test/environments
  data_bags_path: ./test/data_bags
  client_rb:
    environment: kitchen

platforms:
  - name: centos67
    driver_config:
      box: boxcutter/centos67
    attributes:
      system:
        primary_interface: eth1
  - name: centos71
    driver_config:
      box: boxcutter/centos71
    attributes:
      system:
        primary_interface: enp0s8
  - name: centos72
    driver_config:
      box: boxcutter/centos72
    attributes:
      system:
        primary_interface: enp0s8
  - name: ubuntu1404
    driver_config:
      box: boxcutter/ubuntu1404
    attributes:
      system:
        primary_interface: eth1
  - name: ubuntu1504
    driver_config:
      box: boxcutter/ubuntu1504
    attributes:
      system:
        primary_interface: eth1
  - name: debian82
    driver_config:
      box: boxcutter/debian82
    attributes:
      system:
        primary_interface: eth1

suites:
  - name: master
    run_list: ["recipe[masala_ldap::master]"]
    driver:
      vm_hostname: ldap-master.example.com
      network:
      - ["private_network", {ip: "10.10.10.10"}]
      customize:
        memory: 512
        cpus: 1
    attributes:
      openldap:
        basedn: dc=masalatest,dc=com
        rootpw: '{SSHA}ga4ROYIW/lrpyaNCJ2tJp+3UHg8Tq6eU'
        server: localhost
        slapd_master: 10.10.10.10
        tls_enabled: false
        tls_checkpeer: false
        syncrepl_dn: cn=syncrole,dc=masalatest,dc=com
        slapd_replpw: 'my_repl_pw'
      masala_ldap:
        rootpw_clear: devuser
  - name: replica
    run_list: ["recipe[masala_ldap::slave]"]
    driver:
      vm_hostname: ldap-replica1.example.com
      network:
      - ["private_network", {ip: "10.10.10.11"}]
      customize:
        memory: 512
        cpus: 1
    attributes:
      openldap:
        basedn: dc=masalatest,dc=com
        rootpw: '{SSHA}ga4ROYIW/lrpyaNCJ2tJp+3UHg8Tq6eU'
        server: localhost
        tls_enabled: false
        tls_checkpeer: false
        slapd_master: 10.10.10.10
        slapd_rid: 102
        syncrepl_filter: '(objectClass=*)'
        syncrepl_use_tls: 'no'
        syncrepl_dn: cn=syncrole,dc=masalatest,dc=com
        slapd_replpw: 'my_repl_pw'
      masala_ldap:
        rootpw_clear: devuser

